language: node_js
node_js:
- node
notifications:
  email: false
cache: yarn
script: yarn test
deploy:
- provider: npm
  skip_cleanup: true
  email: tminier01@gmail.com
  api_key: $NPM_KEY
  on:
    tags: true
